config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles

  # request to root will map to index action of welcome controller
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
 
  # A frequent practice is to place the standard CRUD actions 
  # in each controller in the following order: index, show, 
  # new, edit, create, update and destroy. 
  def index
    @articles = Article.all
  end

  def show
    # finding article via path param
    @article = Article.find(params[:id])
  end

  def new
  end

  def edit
    @article = Article.find(params[:id])
  end

  # create action /articles/create
  def create
    # creates model, only allowing title and text
    @article = Article.new(article_params)

    # saves to database
    if @article.save
      # rediects to the show action
      redirect_to @article
    else 
      # renders form
      render 'new' 
    end
  end

  def update
    # retrieving
    @article = Article.find(params[:id])

    if(@article.update(article_params))
      redirect_to @article
    else 
      render 'edit'
    end
  end


  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1> Edit article </h1>

<%= form_with(model: @article) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved.
      </h2>
      <ul>  
        <% @article.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %> <br />
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %> <br />
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td> <%= link_to 'show', article_path(article) %></td>
    <td> <%= link_to 'edit', edit_article_path(article) %> </td>
  </tr>
<% end %>

</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path , local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved.
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li> <%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title %> <br />
    <%= form.text_field :title %> 
  </div>

  <div>
    <%= form.label :text %> <br />
    <%= form.text_area :text %> 
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'edit', edit_article_path(@article) %>
<%= link_to 'back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello rails</h1>
<%= link_to 'my blog', controller: 'articles' %>